---
"name": "Release"
"on":
  "push":
    "branches":
      - "main"
"permissions": {}
"concurrency":
  "group": "Release-${{ github.ref }}"
  "cancel-in-progress": false
"defaults":
  "run":
    "shell": "bash"
"env":
  "PYTHONDONTWRITEBYTECODE": 1
  "UV_NO_SYNC": 1
"run-name": "Release"
"jobs":
  "executable":
    "name": "Executable"
    "permissions":
      "contents": "read"
    "runs-on": "${{ matrix.os }}"
    "strategy":
      "matrix":
        "os":
          - "ubuntu-latest"
          - "windows-latest"
          - "macos-latest"
      "fail-fast": true
    "steps":
      -
        "name": "Checkout Repository"
        "id": "checkout-repository"
        "uses": "actions/checkout@main"
        "with":
          "persist-credentials": false
      -
        "name": "Setup Package Manager"
        "id": "setup-package-manager"
        "uses": "astral-sh/setup-uv@main"
        "with":
          "python-version": "3.13"
      -
        "name": "Install Dependencies"
        "id": "install-dependencies"
        "run": "uv sync"
      -
        "name": "Install Pyside System Dependencies"
        "id": "install-pyside-system-dependencies"
        "if": "runner.os == 'Linux'"
        "run": |-
          sudo \
          apt-get \
          update \
          && \
          sudo \
          apt-get \
          install \
          -y \
          libegl1 \
          libpulse0
      -
        "name": "Build Executable"
        "id": "build-executable"
        "run": |-
          uv \
          run \
          pyinstaller \
          --onefile \
          --name=video-vault-${{ runner.os }} \
          --icon=src/video_vault/rig/resources/icon.png \
          --collect-all=video_vault.core.db.migrations \
          --collect-data=video_vault.rig.resources \
          --collect-data=winipyside.rig.resources \
          src/video_vault/main.py
      -
        "name": "Upload Executable"
        "id": "upload-executable"
        "uses": "actions/upload-artifact@main"
        "with":
          "name": "executable-${{ runner.os }}"
          "path": "dist"
  "health-check":
    "name": "Health Check"
    "permissions":
      "contents": "read"
    "uses": "$/.github/workflows/health_check.yml"
  "publish":
    "name": "Publish"
    "permissions":
      "contents": "write"
    "needs":
      - "health-check"
      - "executable"
    "runs-on": "ubuntu-latest"
    "environment": "publish"
    "steps":
      -
        "name": "Checkout Repository"
        "id": "checkout-repository"
        "uses": "actions/checkout@main"
        "with":
          "persist-credentials": false
      -
        "name": "Setup Package Manager"
        "id": "setup-package-manager"
        "uses": "astral-sh/setup-uv@main"
        "with":
          "python-version": "3.13"
      -
        "name": "Configure Repository"
        "id": "configure-repository"
        "run": "bash .github/configure.sh"
        "env":
          "GH_TOKEN": "${{ secrets.REPO_TOKEN }}"
      -
        "name": "Download Executables"
        "id": "download-executables"
        "uses": "actions/download-artifact@main"
        "with":
          "pattern": "executable-*"
          "path": "dist"
          "merge-multiple": "true"
      -
        "name": "Create Release"
        "id": "create-release"
        "run": |-
          gh \
          release \
          create \
          $(uv version --short) \
          dist/* \
          --title=$(uv version --short) \
          --generate-notes
        "env":
          "GH_TOKEN": "${{ secrets.GITHUB_TOKEN }}"
  "deploy":
    "name": "Deploy"
    "permissions":
      "contents": "read"
      "id-token": "write"
      "pages": "write"
    "needs":
      - "publish"
    "uses": "$/.github/workflows/deploy.yml"
    "secrets":
      "REPO_TOKEN": "${{ secrets.REPO_TOKEN }}"
...
